
import styles from '../../styles/Home.module.scss'
import Head from 'next/head'

export default function Works() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div className="wa">
      <Head>
        <title>Works | Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        これが事例
      </main>

    </div>
    </div>
  )
}
